(load-file "~/.elisp/cedet/common/cedet.el")
(require 'ecb)
(setq ecb-tip-of-the-day nil)
(setq ecb-vc-enable-support t)
(setq ecb-layout-name "left9")
(setq ecb-primary-secondary-mouse-buttons (quote mouse-1--C-mouse-1))
(setq global-semantic-auto-parse-mode t)
(setq semantic-load-turn-useful-things-on t)
(semantic-load-enable-excessive-code-helpers)

