 (require 'erc)
 (require 'erc-nick-colors)
 (setq erc-auto-query (quote window))
 (setq erc-autojoin-channels-alist (quote (("freenode.net" "#dingil deviance" "#kubuntu-kde4" "#kubuntu-devel" "#ubuntu-motu"))))
 (setq rc-dcc-mode t)
 (setq erc-email-userid "ismail")
 (setq erc-generate-log-file-name-function (quote erc-generate-log-file-name-short))
 (setq erc-hecomplete-mode t)
 (setq erc-identd-port t)
 (setq erc-kill-buffer-on-part t)
 (setq erc-log-channels t)
 (setq erc-log-channels-directory "~/.irclogs")
 (setq erc-log-mode t)
 (setq erc-minibuffer-notice t)
 (setq erc-modules (quote (autojoin button completion fill identd irccontrols log match menu netsplit noncommands notify readonly ring services smiley stamp track)))
 (setq erc-nick "cartman")
 (setq erc-nick-uniquifier "`")
 (setq erc-notify-mode t)
 (setq erc-page-mode t)
 (setq erc-port 7000)
 (setq erc-prompt-for-channel-key t)
 (setq erc-prompt-for-password t)
 (setq erc-quit-reason (quote erc-quit-reason-zippy))
 (setq erc-server "irc.freenode.net")
 (setq erc-server-send-ping-timeout 60)
 (setq erc-show-channel-key-p nil)
 (setq erc-system-name "ismail")
 (setq erc-track-shorten-function nil)
 (setq erc-track-showcount nil)
 (setq erc-try-new-nick-p t)
 (setq erc-user-full-name "ismail")
 (setq erc-whowas-on-nosuchnick t)
 (setq erc-log-insert-log-on-open nil)
 (setq erc-timestamp-format "[%H:%M] ")
 (setq erc-insert-timestamp-function 'erc-insert-timestamp-left)
 (setq erc-kill-queries-on-quit t)
 (setq erc-kill-server-buffer-on-quit t)
