(let* ((cygwin-root "c:/cygwin")
       (cygwin-bin (concat cygwin-root "/bin")))
  (setenv "PATH" (concat cygwin-bin ";" (getenv "PATH")))
  (setq exec-path (cons cygwin-bin exec-path)))

;;(setq shell-file-name "zsh")
;;(setq explicit-shell-file-name "zsh")
(defun set-shell-cmdproxy()
  (interactive)
  (setq shell-file-name "cmdproxy")
  (setq explicit-shell-file-name "cmdproxy")
  (setenv "SHELL" explicit-shell-file-name)
  (setq w32-quote-process-args t)
  (setq shell-command-switch "/c")
  )

(set-shell-cmdproxy)
